### ISSUE TITLE
Relation to other extensions?

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/render#3]
Why are some of the fields redefined here although alternative exist?

For example:
- nodata => raster:bands[*].nodata
- colormap => classification:classes
- rescale => raster:bands[*].statistics

**Comment by emmanuelmathot** [comment]
This is not redefinition of fields but fixed settings for how to render a specific view of an item or asset.

**Comment by emmanuelmathot** [comment]
Closing staled issue with previous comment
